apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi2-platform-controller-manager
  namespace: nifi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nifi2-platform-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nifi2-platform-controller-manager
    spec:
      serviceAccountName: nifi2-platform-controller-manager
      containers:
      - name: manager
        image: nifi2-platform-controller:dev
        imagePullPolicy: Never
        args:
        - --leader-elect
        ports:
        - name: metrics
          containerPort: 8080
        - name: probes
          containerPort: 8081
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
