{{- if eq (include "nifi-platform.managedMode" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nifi-platform.controllerServiceAccountName" . }}
  namespace: {{ include "nifi-platform.controllerNamespace" . }}
  labels:
    {{- include "nifi-platform.labels" . | nindent 4 }}
{{- end }}
