apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nifi2-platform-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nifi2-platform-controller-manager
subjects:
- kind: ServiceAccount
  name: nifi2-platform-controller-manager
  namespace: nifi-system

