apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifi-fabric-controller-manager
rules:
- apiGroups:
  - platform.nifi.io
  resources:
  - nificlusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.nifi.io
  resources:
  - nificlusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
