apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) (include "nifi.linkerdServiceAnnotations" (dict "root" . "servicePorts" (list .Values.ports.https)) | fromYaml) (default (dict) .Values.service.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: {{ .Values.ports.https }}
    protocol: TCP
    targetPort: https
