//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingExecutionStatus) DeepCopyInto(out *AutoscalingExecutionStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.TargetReplicas != nil {
		in, out := &in.TargetReplicas, &out.TargetReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingExecutionStatus.
func (in *AutoscalingExecutionStatus) DeepCopy() *AutoscalingExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingExternalPolicy) DeepCopyInto(out *AutoscalingExternalPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingExternalPolicy.
func (in *AutoscalingExternalPolicy) DeepCopy() *AutoscalingExternalPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingExternalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingExternalStatus) DeepCopyInto(out *AutoscalingExternalStatus) {
	*out = *in
	if in.RequestedReplicas != nil {
		in, out := &in.RequestedReplicas, &out.RequestedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.BoundedReplicas != nil {
		in, out := &in.BoundedReplicas, &out.BoundedReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingExternalStatus.
func (in *AutoscalingExternalStatus) DeepCopy() *AutoscalingExternalStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingExternalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingLowPressureStatus) DeepCopyInto(out *AutoscalingLowPressureStatus) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
	if in.LastObservedAt != nil {
		in, out := &in.LastObservedAt, &out.LastObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingLowPressureStatus.
func (in *AutoscalingLowPressureStatus) DeepCopy() *AutoscalingLowPressureStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingLowPressureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	out.ScaleUp = in.ScaleUp
	out.ScaleDown = in.ScaleDown
	out.External = in.External
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]AutoscalingSignal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingScaleDownPolicy) DeepCopyInto(out *AutoscalingScaleDownPolicy) {
	*out = *in
	out.Cooldown = in.Cooldown
	out.StabilizationWindow = in.StabilizationWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingScaleDownPolicy.
func (in *AutoscalingScaleDownPolicy) DeepCopy() *AutoscalingScaleDownPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingScaleDownPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingScaleUpPolicy) DeepCopyInto(out *AutoscalingScaleUpPolicy) {
	*out = *in
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingScaleUpPolicy.
func (in *AutoscalingScaleUpPolicy) DeepCopy() *AutoscalingScaleUpPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingScaleUpPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSignalStatus) DeepCopyInto(out *AutoscalingSignalStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSignalStatus.
func (in *AutoscalingSignalStatus) DeepCopy() *AutoscalingSignalStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSignalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingStatus) DeepCopyInto(out *AutoscalingStatus) {
	*out = *in
	if in.RecommendedReplicas != nil {
		in, out := &in.RecommendedReplicas, &out.RecommendedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]AutoscalingSignalStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.LowPressureSince != nil {
		in, out := &in.LowPressureSince, &out.LowPressureSince
		*out = (*in).DeepCopy()
	}
	in.LowPressure.DeepCopyInto(&out.LowPressure)
	if in.LastScaleUpTime != nil {
		in, out := &in.LastScaleUpTime, &out.LastScaleUpTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDownTime != nil {
		in, out := &in.LastScaleDownTime, &out.LastScaleDownTime
		*out = (*in).DeepCopy()
	}
	in.Execution.DeepCopyInto(&out.Execution)
	in.External.DeepCopyInto(&out.External)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingStatus.
func (in *AutoscalingStatus) DeepCopy() *AutoscalingStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodesStatus) DeepCopyInto(out *ClusterNodesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodesStatus.
func (in *ClusterNodesStatus) DeepCopy() *ClusterNodesStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNodesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowRolloutPolicy) DeepCopyInto(out *DataflowRolloutPolicy) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowRolloutPolicy.
func (in *DataflowRolloutPolicy) DeepCopy() *DataflowRolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(DataflowRolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowSource) DeepCopyInto(out *DataflowSource) {
	*out = *in
	out.RegistryClient = in.RegistryClient
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowSource.
func (in *DataflowSource) DeepCopy() *DataflowSource {
	if in == nil {
		return nil
	}
	out := new(DataflowSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowSyncPolicy) DeepCopyInto(out *DataflowSyncPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowSyncPolicy.
func (in *DataflowSyncPolicy) DeepCopy() *DataflowSyncPolicy {
	if in == nil {
		return nil
	}
	out := new(DataflowSyncPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowTarget) DeepCopyInto(out *DataflowTarget) {
	*out = *in
	if in.ParameterContextRef != nil {
		in, out := &in.ParameterContextRef, &out.ParameterContextRef
		*out = new(ParameterContextRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowTarget.
func (in *DataflowTarget) DeepCopy() *DataflowTarget {
	if in == nil {
		return nil
	}
	out := new(DataflowTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationPolicy) DeepCopyInto(out *HibernationPolicy) {
	*out = *in
	out.OffloadTimeout = in.OffloadTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationPolicy.
func (in *HibernationPolicy) DeepCopy() *HibernationPolicy {
	if in == nil {
		return nil
	}
	out := new(HibernationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationStatus) DeepCopyInto(out *HibernationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationStatus.
func (in *HibernationStatus) DeepCopy() *HibernationStatus {
	if in == nil {
		return nil
	}
	out := new(HibernationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastOperation) DeepCopyInto(out *LastOperation) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastOperation.
func (in *LastOperation) DeepCopy() *LastOperation {
	if in == nil {
		return nil
	}
	out := new(LastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiCluster) DeepCopyInto(out *NiFiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiCluster.
func (in *NiFiCluster) DeepCopy() *NiFiCluster {
	if in == nil {
		return nil
	}
	out := new(NiFiCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterList) DeepCopyInto(out *NiFiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterList.
func (in *NiFiClusterList) DeepCopy() *NiFiClusterList {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterRef) DeepCopyInto(out *NiFiClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterRef.
func (in *NiFiClusterRef) DeepCopy() *NiFiClusterRef {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterSpec) DeepCopyInto(out *NiFiClusterSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.RestartTriggers.DeepCopyInto(&out.RestartTriggers)
	out.RestartPolicy = in.RestartPolicy
	out.Rollout = in.Rollout
	out.Hibernation = in.Hibernation
	out.Safety = in.Safety
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterSpec.
func (in *NiFiClusterSpec) DeepCopy() *NiFiClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterStatus) DeepCopyInto(out *NiFiClusterStatus) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
	in.Rollout.DeepCopyInto(&out.Rollout)
	out.Replicas = in.Replicas
	out.ClusterNodes = in.ClusterNodes
	out.Hibernation = in.Hibernation
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.NodeOperation.DeepCopyInto(&out.NodeOperation)
	in.LastOperation.DeepCopyInto(&out.LastOperation)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterStatus.
func (in *NiFiClusterStatus) DeepCopy() *NiFiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiDataflow) DeepCopyInto(out *NiFiDataflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiDataflow.
func (in *NiFiDataflow) DeepCopy() *NiFiDataflow {
	if in == nil {
		return nil
	}
	out := new(NiFiDataflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiDataflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiDataflowList) DeepCopyInto(out *NiFiDataflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiDataflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiDataflowList.
func (in *NiFiDataflowList) DeepCopy() *NiFiDataflowList {
	if in == nil {
		return nil
	}
	out := new(NiFiDataflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiDataflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiDataflowSpec) DeepCopyInto(out *NiFiDataflowSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.Source = in.Source
	in.Target.DeepCopyInto(&out.Target)
	out.Rollout = in.Rollout
	out.SyncPolicy = in.SyncPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiDataflowSpec.
func (in *NiFiDataflowSpec) DeepCopy() *NiFiDataflowSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiDataflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiDataflowStatus) DeepCopyInto(out *NiFiDataflowStatus) {
	*out = *in
	in.LastOperation.DeepCopyInto(&out.LastOperation)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiDataflowStatus.
func (in *NiFiDataflowStatus) DeepCopy() *NiFiDataflowStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiDataflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeOperationStatus) DeepCopyInto(out *NodeOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeOperationStatus.
func (in *NodeOperationStatus) DeepCopy() *NodeOperationStatus {
	if in == nil {
		return nil
	}
	out := new(NodeOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterContextRef) DeepCopyInto(out *ParameterContextRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterContextRef.
func (in *ParameterContextRef) DeepCopy() *ParameterContextRef {
	if in == nil {
		return nil
	}
	out := new(ParameterContextRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryClientRef) DeepCopyInto(out *RegistryClientRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryClientRef.
func (in *RegistryClientRef) DeepCopy() *RegistryClientRef {
	if in == nil {
		return nil
	}
	out := new(RegistryClientRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartPolicy) DeepCopyInto(out *RestartPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartPolicy.
func (in *RestartPolicy) DeepCopy() *RestartPolicy {
	if in == nil {
		return nil
	}
	out := new(RestartPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartTriggers) DeepCopyInto(out *RestartTriggers) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartTriggers.
func (in *RestartTriggers) DeepCopy() *RestartTriggers {
	if in == nil {
		return nil
	}
	out := new(RestartTriggers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPolicy) DeepCopyInto(out *RolloutPolicy) {
	*out = *in
	out.PodReadyTimeout = in.PodReadyTimeout
	out.ClusterHealthTimeout = in.ClusterHealthTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPolicy.
func (in *RolloutPolicy) DeepCopy() *RolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedPods != nil {
		in, out := &in.CompletedPods, &out.CompletedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicy) DeepCopyInto(out *SafetyPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicy.
func (in *SafetyPolicy) DeepCopy() *SafetyPolicy {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSStatus) DeepCopyInto(out *TLSStatus) {
	*out = *in
	if in.ObservationStartedAt != nil {
		in, out := &in.ObservationStartedAt, &out.ObservationStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSStatus.
func (in *TLSStatus) DeepCopy() *TLSStatus {
	if in == nil {
		return nil
	}
	out := new(TLSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
