//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClusterNodesStatus) DeepCopyInto(out *ClusterNodesStatus) {
	*out = *in
}

func (in *ClusterNodesStatus) DeepCopy() *ClusterNodesStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNodesStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	out.ScaleUp = in.ScaleUp
	out.ScaleDown = in.ScaleDown
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]AutoscalingSignal, len(*in))
		copy(*out, *in)
	}
}

func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingSignalStatus) DeepCopyInto(out *AutoscalingSignalStatus) {
	*out = *in
}

func (in *AutoscalingSignalStatus) DeepCopy() *AutoscalingSignalStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSignalStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingStatus) DeepCopyInto(out *AutoscalingStatus) {
	*out = *in
	if in.RecommendedReplicas != nil {
		in, out := &in.RecommendedReplicas, &out.RecommendedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]AutoscalingSignalStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.LowPressureSince != nil {
		in, out := &in.LowPressureSince, &out.LowPressureSince
		*out = (*in).DeepCopy()
	}
	if in.LastScaleUpTime != nil {
		in, out := &in.LastScaleUpTime, &out.LastScaleUpTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDownTime != nil {
		in, out := &in.LastScaleDownTime, &out.LastScaleDownTime
		*out = (*in).DeepCopy()
	}
}

func (in *AutoscalingStatus) DeepCopy() *AutoscalingStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingScaleDownPolicy) DeepCopyInto(out *AutoscalingScaleDownPolicy) {
	*out = *in
}

func (in *AutoscalingScaleDownPolicy) DeepCopy() *AutoscalingScaleDownPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingScaleDownPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingScaleUpPolicy) DeepCopyInto(out *AutoscalingScaleUpPolicy) {
	*out = *in
}

func (in *AutoscalingScaleUpPolicy) DeepCopy() *AutoscalingScaleUpPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingScaleUpPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *HibernationPolicy) DeepCopyInto(out *HibernationPolicy) {
	*out = *in
}

func (in *HibernationPolicy) DeepCopy() *HibernationPolicy {
	if in == nil {
		return nil
	}
	out := new(HibernationPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *HibernationStatus) DeepCopyInto(out *HibernationStatus) {
	*out = *in
}

func (in *HibernationStatus) DeepCopy() *HibernationStatus {
	if in == nil {
		return nil
	}
	out := new(HibernationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *LastOperation) DeepCopyInto(out *LastOperation) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

func (in *LastOperation) DeepCopy() *LastOperation {
	if in == nil {
		return nil
	}
	out := new(LastOperation)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeOperationStatus) DeepCopyInto(out *NodeOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

func (in *NodeOperationStatus) DeepCopy() *NodeOperationStatus {
	if in == nil {
		return nil
	}
	out := new(NodeOperationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *NiFiCluster) DeepCopyInto(out *NiFiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NiFiCluster) DeepCopy() *NiFiCluster {
	if in == nil {
		return nil
	}
	out := new(NiFiCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *NiFiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NiFiClusterList) DeepCopyInto(out *NiFiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NiFiClusterList) DeepCopy() *NiFiClusterList {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *NiFiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NiFiClusterSpec) DeepCopyInto(out *NiFiClusterSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.RestartTriggers.DeepCopyInto(&out.RestartTriggers)
	out.RestartPolicy = in.RestartPolicy
	out.Rollout = in.Rollout
	out.Hibernation = in.Hibernation
	out.Safety = in.Safety
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
}

func (in *NiFiClusterSpec) DeepCopy() *NiFiClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NiFiClusterStatus) DeepCopyInto(out *NiFiClusterStatus) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
	in.Rollout.DeepCopyInto(&out.Rollout)
	out.Replicas = in.Replicas
	out.ClusterNodes = in.ClusterNodes
	out.Hibernation = in.Hibernation
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.NodeOperation.DeepCopyInto(&out.NodeOperation)
	in.LastOperation.DeepCopyInto(&out.LastOperation)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NiFiClusterStatus) DeepCopy() *NiFiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
}

func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RestartPolicy) DeepCopyInto(out *RestartPolicy) {
	*out = *in
}

func (in *RestartPolicy) DeepCopy() *RestartPolicy {
	if in == nil {
		return nil
	}
	out := new(RestartPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *RestartTriggers) DeepCopyInto(out *RestartTriggers) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

func (in *RestartTriggers) DeepCopy() *RestartTriggers {
	if in == nil {
		return nil
	}
	out := new(RestartTriggers)
	in.DeepCopyInto(out)
	return out
}

func (in *TLSStatus) DeepCopyInto(out *TLSStatus) {
	*out = *in
	if in.ObservationStartedAt != nil {
		in, out := &in.ObservationStartedAt, &out.ObservationStartedAt
		*out = (*in).DeepCopy()
	}
}

func (in *TLSStatus) DeepCopy() *TLSStatus {
	if in == nil {
		return nil
	}
	out := new(TLSStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedPods != nil {
		in, out := &in.CompletedPods, &out.CompletedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutPolicy) DeepCopyInto(out *RolloutPolicy) {
	*out = *in
}

func (in *RolloutPolicy) DeepCopy() *RolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *SafetyPolicy) DeepCopyInto(out *SafetyPolicy) {
	*out = *in
}

func (in *SafetyPolicy) DeepCopy() *SafetyPolicy {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
