replicaCount: 3

controllerManaged:
  enabled: true

auth:
  singleUser:
    existingSecret: nifi-auth

tls:
  existingSecret: nifi-tls
  autoReload:
    enabled: true

serviceMonitor:
  enabled: false

nifi:
  jvmHeapInit: 512m
  jvmHeapMax: 512m
