nifi:
  observability:
    metrics:
      siteToSite:
        auth:
          type: secretRef
          secretRef:
            name: nifi-site-to-site-receiver-client
        destination:
          url: https://site-to-site-receiver.site-to-site-receiver.svc.cluster.local:8443/nifi
          inputPortName: nifi-metrics
        source:
          instanceUrl: https://nifi.nifi.svc.cluster.local:8443/nifi
