nifi:
  observability:
    siteToSiteProvenance:
      auth:
        type: secretRef
        authorizedIdentity: O=NiFi-Fabric, CN=nifi-site-to-site-provenance-client
        secretRef:
          name: nifi-site-to-site-receiver-provenance-client
      destination:
        url: https://site-to-site-receiver.site-to-site-receiver.svc.cluster.local:8443/nifi
        inputPortName: nifi-provenance
      source:
        instanceUrl: https://nifi.nifi.svc.cluster.local:8443/nifi
      provenance:
        startPosition: endOfStream
