# Advanced managed example with explicit operator-provided auth and TLS Secrets.
mode: managed

controller:
  namespace:
    name: nifi-system
    create: true
  image:
    repository: nifi-fabric-controller
    tag: dev
    pullPolicy: IfNotPresent

cluster:
  desiredState: Running

nifi:
  replicaCount: 3

  controllerManaged:
    enabled: true

  auth:
    mode: singleUser
    singleUser:
      existingSecret: nifi-auth

  authz:
    mode: fileManaged

  tls:
    mode: externalSecret
    existingSecret: nifi-tls
    autoReload:
      enabled: true

  nifi:
    jvmHeapInit: 512m
    jvmHeapMax: 512m
