package authztool

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadConfigDefaultsGroupValueMode(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	configPath := filepath.Join(dir, "config.yaml")
	if err := os.WriteFile(configPath, []byte(`
source:
  type: keycloak
  baseUrl: https://keycloak.example.com
  realm: nifi
  groupsClaim: groups

authz:
  initialAdminGroup: nifi-platform-admins

bindings:
- keycloakGroup: nifi-platform-admins
  bundles: [admin]
`), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}

	cfg, err := LoadConfig(configPath)
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	if got, want := cfg.Source.GroupValueMode, GroupValueModeName; got != want {
		t.Fatalf("group value mode = %q, want %q", got, want)
	}
}

func TestRenderConfigAppSurface(t *testing.T) {
	t.Parallel()

	cfg := Config{
		Source: SourceConfig{
			Type:           SourceTypeKeycloak,
			BaseURL:        "https://keycloak.example.com",
			Realm:          "nifi",
			GroupsClaim:    "groups",
			GroupValueMode: GroupValueModeName,
		},
		Authz: AuthzConfig{
			InitialAdminGroup: "nifi-platform-admins",
		},
		Bindings: []Binding{
			{KeycloakGroup: "nifi-platform-admins", Bundles: []string{"admin"}},
			{KeycloakGroup: "nifi-flow-operators", Bundles: []string{"editor", "flowVersionManager", "viewer"}},
			{KeycloakGroup: "nifi-flow-observers", Bundles: []string{"viewer"}},
		},
	}

	rendered, err := RenderConfig(cfg, RenderOptions{
		Surface:       SurfaceApp,
		HeaderComment: true,
	})
	if err != nil {
		t.Fatalf("render config: %v", err)
	}

	want := `# Code generated by nifi-fabric-authz; DO NOT EDIT.
authz:
    mode: externalClaimGroups
    bootstrap:
        initialAdminGroup: nifi-platform-admins
    applicationGroups:
        - nifi-flow-observers
        - nifi-flow-operators
        - nifi-platform-admins
    bundles:
        viewer:
            groups:
                - nifi-flow-observers
                - nifi-flow-operators
        editor:
            groups:
                - nifi-flow-operators
        flowVersionManager:
            groups:
                - nifi-flow-operators
        admin:
            groups:
                - nifi-platform-admins
`

	if got := string(rendered); got != want {
		t.Fatalf("rendered output mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
}

func TestRenderConfigPlatformSurfaceWithAuthSection(t *testing.T) {
	t.Parallel()

	cfg := Config{
		Source: SourceConfig{
			Type:           SourceTypeKeycloak,
			BaseURL:        "https://keycloak.example.com",
			Realm:          "nifi",
			GroupsClaim:    "groups",
			GroupValueMode: GroupValueModeName,
		},
		Authz: AuthzConfig{
			InitialAdminGroup: "nifi-platform-admins",
		},
		Bindings: []Binding{
			{KeycloakGroup: "nifi-platform-admins", Bundles: []string{"admin"}},
		},
	}

	rendered, err := RenderConfig(cfg, RenderOptions{
		Surface:            SurfacePlatform,
		IncludeAuthSection: true,
		HeaderComment:      true,
	})
	if err != nil {
		t.Fatalf("render config: %v", err)
	}

	want := `# Code generated by nifi-fabric-authz; DO NOT EDIT.
nifi:
    auth:
        mode: oidc
        oidc:
            claims:
                groups: groups
    authz:
        mode: externalClaimGroups
        bootstrap:
            initialAdminGroup: nifi-platform-admins
        applicationGroups:
            - nifi-platform-admins
        bundles:
            admin:
                groups:
                    - nifi-platform-admins
`

	if got := string(rendered); got != want {
		t.Fatalf("rendered output mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
}

func TestValidateKeycloakMappingsDetectsDuplicatesInNameMode(t *testing.T) {
	t.Parallel()

	server := newKeycloakTestServer(t)
	cfg := Config{
		Source: SourceConfig{
			Type:           SourceTypeKeycloak,
			BaseURL:        server.URL,
			Realm:          "nifi",
			GroupsClaim:    "groups",
			GroupValueMode: GroupValueModeName,
		},
		Authz: AuthzConfig{
			InitialAdminGroup: "nifi-platform-admins",
		},
		Bindings: []Binding{
			{KeycloakGroup: "nifi-platform-admins", Bundles: []string{"admin"}},
		},
	}

	err := ValidateKeycloakMappings(context.Background(), cfg, Credentials{
		AccessToken: "test-token",
	})
	if err == nil {
		t.Fatalf("expected validation error")
	}
	if !strings.Contains(err.Error(), `duplicate Keycloak group value "nifi-platform-admins"`) {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestValidateKeycloakMappingsSupportsPathMode(t *testing.T) {
	t.Parallel()

	server := newKeycloakTestServer(t)
	cfg := Config{
		Source: SourceConfig{
			Type:           SourceTypeKeycloak,
			BaseURL:        server.URL,
			Realm:          "nifi",
			GroupsClaim:    "groups",
			GroupValueMode: GroupValueModePath,
		},
		Authz: AuthzConfig{
			InitialAdminGroup: "/ops/nifi-platform-admins",
		},
		Bindings: []Binding{
			{KeycloakGroup: "/ops/nifi-platform-admins", Bundles: []string{"admin"}},
			{KeycloakGroup: "/apps/nifi-platform-admins", Bundles: []string{"viewer"}},
		},
	}

	if err := ValidateKeycloakMappings(context.Background(), cfg, Credentials{
		AccessToken: "test-token",
	}); err != nil {
		t.Fatalf("validate keycloak mappings: %v", err)
	}
}

func TestValidateKeycloakMappingsCallsOutClaimShapeMismatch(t *testing.T) {
	t.Parallel()

	server := newKeycloakTestServer(t)
	cfg := Config{
		Source: SourceConfig{
			Type:           SourceTypeKeycloak,
			BaseURL:        server.URL,
			Realm:          "nifi",
			GroupsClaim:    "groups",
			GroupValueMode: GroupValueModeName,
		},
		Authz: AuthzConfig{
			InitialAdminGroup: "/ops/nifi-platform-admins",
		},
		Bindings: []Binding{
			{KeycloakGroup: "/ops/nifi-platform-admins", Bundles: []string{"admin"}},
		},
	}

	err := ValidateKeycloakMappings(context.Background(), cfg, Credentials{
		AccessToken: "test-token",
	})
	if err == nil {
		t.Fatalf("expected validation error")
	}
	if !strings.Contains(err.Error(), `exists in Keycloak but only matches the path claim shape`) {
		t.Fatalf("unexpected error: %v", err)
	}
}

func newKeycloakTestServer(t *testing.T) *httptest.Server {
	t.Helper()

	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/admin/realms/nifi/groups":
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`[
  {"name":"ops","path":"/ops","subGroups":[{"name":"nifi-platform-admins","path":"/ops/nifi-platform-admins","subGroups":[]}]},
  {"name":"apps","path":"/apps","subGroups":[{"name":"nifi-platform-admins","path":"/apps/nifi-platform-admins","subGroups":[]}]}
]`))
		default:
			http.NotFound(w, r)
		}
	}))
}
