package authztool

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

type Surface string

const (
	SurfaceApp      Surface = "app"
	SurfacePlatform Surface = "platform"
)

type RenderOptions struct {
	Surface            Surface
	IncludeAuthSection bool
	HeaderComment      bool
}

type appOverlay struct {
	Auth  *authSection `yaml:"auth,omitempty"`
	Authz authzSection `yaml:"authz"`
}

type platformOverlay struct {
	NiFi nifiOverlay `yaml:"nifi"`
}

type nifiOverlay struct {
	Auth  *authSection `yaml:"auth,omitempty"`
	Authz authzSection `yaml:"authz"`
}

type authSection struct {
	Mode string      `yaml:"mode"`
	OIDC oidcSection `yaml:"oidc"`
}

type oidcSection struct {
	Claims oidcClaims `yaml:"claims"`
}

type oidcClaims struct {
	Groups string `yaml:"groups"`
}

type authzSection struct {
	Mode              string        `yaml:"mode"`
	Bootstrap         bootstrap     `yaml:"bootstrap"`
	ApplicationGroups []string      `yaml:"applicationGroups"`
	Bundles           bundleTargets `yaml:"bundles"`
}

type bootstrap struct {
	InitialAdminGroup string `yaml:"initialAdminGroup"`
}

type bundleTargets struct {
	Viewer             *bundleGroupList `yaml:"viewer,omitempty"`
	Editor             *bundleGroupList `yaml:"editor,omitempty"`
	FlowVersionManager *bundleGroupList `yaml:"flowVersionManager,omitempty"`
	Admin              *bundleGroupList `yaml:"admin,omitempty"`
}

type bundleGroupList struct {
	Groups []string `yaml:"groups"`
}

func ParseSurface(value string) (Surface, error) {
	switch Surface(value) {
	case SurfaceApp:
		return SurfaceApp, nil
	case SurfacePlatform:
		return SurfacePlatform, nil
	default:
		return "", fmt.Errorf("surface must be %q or %q", SurfaceApp, SurfacePlatform)
	}
}

func RenderConfig(cfg Config, opts RenderOptions) ([]byte, error) {
	authz := authzSection{
		Mode:              "externalClaimGroups",
		Bootstrap:         bootstrap{InitialAdminGroup: cfg.Authz.InitialAdminGroup},
		ApplicationGroups: cfg.DerivedApplicationGroups(),
		Bundles:           buildBundleTargets(cfg.BundleGroups()),
	}

	var payload any
	authSection := buildAuthSection(cfg.Source.GroupsClaim, opts.IncludeAuthSection)

	switch opts.Surface {
	case SurfaceApp:
		payload = appOverlay{
			Auth:  authSection,
			Authz: authz,
		}
	case SurfacePlatform:
		payload = platformOverlay{
			NiFi: nifiOverlay{
				Auth:  authSection,
				Authz: authz,
			},
		}
	default:
		return nil, fmt.Errorf("unsupported surface %q", opts.Surface)
	}

	raw, err := yaml.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("marshal overlay: %w", err)
	}

	if !opts.HeaderComment {
		return raw, nil
	}

	var out bytes.Buffer
	out.WriteString("# Code generated by nifi-fabric-authz; DO NOT EDIT.\n")
	out.Write(raw)
	return out.Bytes(), nil
}

func buildAuthSection(groupsClaim string, include bool) *authSection {
	if !include {
		return nil
	}
	return &authSection{
		Mode: "oidc",
		OIDC: oidcSection{
			Claims: oidcClaims{
				Groups: groupsClaim,
			},
		},
	}
}

func buildBundleTargets(groups map[string][]string) bundleTargets {
	targets := bundleTargets{}
	if len(groups["viewer"]) > 0 {
		targets.Viewer = &bundleGroupList{Groups: groups["viewer"]}
	}
	if len(groups["editor"]) > 0 {
		targets.Editor = &bundleGroupList{Groups: groups["editor"]}
	}
	if len(groups["flowVersionManager"]) > 0 {
		targets.FlowVersionManager = &bundleGroupList{Groups: groups["flowVersionManager"]}
	}
	if len(groups["admin"]) > 0 {
		targets.Admin = &bundleGroupList{Groups: groups["admin"]}
	}
	return targets
}
